### ISSUE TITLE
worker_manager_loop import error

### ISSUE THREAD

**Issue by ajinkya933** [fperazzi/proSR#43]
I am using macOS and executing your code using 

`python test.py --checkpoint data/checkpoints/proSR.pth --target data/datasets/DIV2K/DIV2K_valid_HR --scale 8`

I am getting the following error

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    from prosr.data import DataLoader, Dataset, DataChunks
  File "/Users/ajinkyabobade/Downloads/proSR-master/lib/prosr/data/__init__.py", line 1, in <module>
    from .progressive_loader import DataLoader, Dataset
  File "/Users/ajinkyabobade/Downloads/proSR-master/lib/prosr/data/progressive_loader.py", line 1, in <module>
    from . import multiproc
  File "/Users/ajinkyabobade/Downloads/proSR-master/lib/prosr/data/multiproc.py", line 3, in <module>
    from torch.utils.data.dataloader import (_DataLoaderIter, DataLoader,
ImportError: cannot import name '_worker_manager_loop' from 'torch.utils.data.dataloader' (/anaconda3/envs/proSR/lib/python3.7/site-packages/torch/utils/data/dataloader.py)
```

How can I remove this error and run test.py ?

I tried the solution entered here : https://github.com/fperazzi/proSR/issues/31

But then I get 

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    from prosr.data import DataLoader, Dataset, DataChunks
  File "/Users/ajinkyabobade/Downloads/proSR-master/lib/prosr/data/__init__.py", line 1, in <module>
    from .progressive_loader import DataLoader, Dataset
  File "/Users/ajinkyabobade/Downloads/proSR-master/lib/prosr/data/progressive_loader.py", line 1, in <module>
    from . import multiproc
  File "/Users/ajinkyabobade/Downloads/proSR-master/lib/prosr/data/multiproc.py", line 3, in <module>
    from torch.utils.data.dataloader import (_DataLoaderIter, DataLoader,
ImportError: cannot import name '_pin_memory_loop' from 'torch.utils.data.dataloader' (/anaconda3/envs/proSR/lib/python3.7/site-packages/torch/utils/data/dataloader.py)

```

**Comment by ajinkya933** [comment]
I solved it by

- git clone https://github.com/fperazzi/proSR.git

-             else:
                input = data['input']
                """
                if not args.cpu:
                    input = input.cuda()
                    """
                output = model(input,args.scale).cpu() + data['bicubic']

Comment the lines in proSR-master from 

> if not args.cpu

: as shown above

**Comment by ManoaNosea** [comment]
thank :), this work on 3.6 or only 3.7 ?

**Comment by ajinkya933** [comment]
I tested it only on python 3.6

**Comment by joshhansen** [comment]
This issue is closed but I'm getting this error on current master FYI when running test.py. pytorch==1.0.0

**Comment by Jimzhou82sub** [comment]
@joshhansen  of course , when pytorch ==1.0.0, some functions have been removed
